# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_comprobante_siif.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_comprobante_siif(object):
    def setupUi(self, form_comprobante_siif):
        form_comprobante_siif.setObjectName("form_comprobante_siif")
        form_comprobante_siif.setWindowModality(QtCore.Qt.NonModal)
        form_comprobante_siif.resize(574, 275)
        form_comprobante_siif.setSizeGripEnabled(False)
        form_comprobante_siif.setModal(False)
        self.btn_box = QtWidgets.QDialogButtonBox(form_comprobante_siif)
        self.btn_box.setGeometry(QtCore.QRect(10, 240, 551, 32))
        self.btn_box.setOrientation(QtCore.Qt.Horizontal)
        self.btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.btn_box.setObjectName("btn_box")
        self.lbl_img = QtWidgets.QLabel(form_comprobante_siif)
        self.lbl_img.setGeometry(QtCore.QRect(10, 10, 191, 231))
        self.lbl_img.setText("")
        self.lbl_img.setPixmap(QtGui.QPixmap("../static/images/form_comprobantes_siif.jpg"))
        self.lbl_img.setScaledContents(True)
        self.lbl_img.setObjectName("lbl_img")
        self.frame = QtWidgets.QFrame(form_comprobante_siif)
        self.frame.setGeometry(QtCore.QRect(210, 10, 351, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_titulo = QtWidgets.QLabel(self.frame)
        self.lbl_titulo.setGeometry(QtCore.QRect(6, 2, 341, 31))
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 40, 351, 191))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(5, 20, 10, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.txt_nro_entrada = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_nro_entrada.setObjectName("txt_nro_entrada")
        self.gridLayout.addWidget(self.txt_nro_entrada, 0, 1, 1, 1)
        self.lbl_partida = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_partida.setObjectName("lbl_partida")
        self.gridLayout.addWidget(self.lbl_partida, 3, 0, 1, 1)
        self.cmb_tipo = QtWidgets.QComboBox(self.layoutWidget)
        self.cmb_tipo.setObjectName("cmb_tipo")
        self.gridLayout.addWidget(self.cmb_tipo, 3, 1, 1, 1)
        self.lbl_estructura = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_estructura.setObjectName("lbl_estructura")
        self.gridLayout.addWidget(self.lbl_estructura, 0, 2, 1, 1)
        self.lbl_nombre = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.gridLayout.addWidget(self.lbl_nombre, 0, 0, 1, 1)
        self.dat_fecha = QtWidgets.QDateEdit(self.layoutWidget)
        self.dat_fecha.setObjectName("dat_fecha")
        self.gridLayout.addWidget(self.dat_fecha, 0, 3, 1, 1)

        self.retranslateUi(form_comprobante_siif)
        self.btn_box.accepted.connect(form_comprobante_siif.accept) # type: ignore
        self.btn_box.rejected.connect(form_comprobante_siif.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(form_comprobante_siif)

    def retranslateUi(self, form_comprobante_siif):
        _translate = QtCore.QCoreApplication.translate
        form_comprobante_siif.setWindowTitle(_translate("form_comprobante_siif", "Agregar / Editar Comprobante SIIF"))
        self.lbl_titulo.setText(_translate("form_comprobante_siif", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Agregar SIIF</span></p></body></html>"))
        self.lbl_partida.setText(_translate("form_comprobante_siif", "Tipo"))
        self.lbl_estructura.setText(_translate("form_comprobante_siif", "Fecha"))
        self.lbl_nombre.setText(_translate("form_comprobante_siif", "Nro Comprobante"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_comprobante_siif = QtWidgets.QDialog()
    ui = Ui_form_comprobante_siif()
    ui.setupUi(form_comprobante_siif)
    form_comprobante_siif.show()
    sys.exit(app.exec_())
