# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(484, 379)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mdi_area = QtWidgets.QMdiArea(self.centralwidget)
        self.mdi_area.setObjectName("mdi_area")
        self.gridLayout.addWidget(self.mdi_area, 0, 0, 1, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 21))
        self.menubar.setObjectName("menubar")
        self.mnu_archivo = QtWidgets.QMenu(self.menubar)
        self.mnu_archivo.setObjectName("mnu_archivo")
        self.menuFactureros = QtWidgets.QMenu(self.mnu_archivo)
        self.menuFactureros.setObjectName("menuFactureros")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.mnu_add_facturero = QtWidgets.QAction(main_window)
        self.mnu_add_facturero.setObjectName("mnu_add_facturero")
        self.mnu_listado_factureros = QtWidgets.QAction(main_window)
        self.mnu_listado_factureros.setObjectName("mnu_listado_factureros")
        self.menuFactureros.addAction(self.mnu_add_facturero)
        self.menuFactureros.addAction(self.mnu_listado_factureros)
        self.mnu_archivo.addAction(self.menuFactureros.menuAction())
        self.menubar.addAction(self.mnu_archivo.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Slave"))
        self.mnu_archivo.setTitle(_translate("main_window", "Archivo"))
        self.menuFactureros.setTitle(_translate("main_window", "Factureros"))
        self.mnu_add_facturero.setText(_translate("main_window", "Nuevo Facturero"))
        self.mnu_listado_factureros.setText(_translate("main_window", "Listado Factureros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
