# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_factureros.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_factureros(object):
    def setupUi(self, table_factureros):
        table_factureros.setObjectName("table_factureros")
        table_factureros.resize(450, 500)
        self.gridLayout = QtWidgets.QGridLayout(table_factureros)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_test = QtWidgets.QLabel(table_factureros)
        self.lbl_test.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test.setObjectName("lbl_test")
        self.gridLayout.addWidget(self.lbl_test, 3, 0, 1, 1)
        self.frame = QtWidgets.QFrame(table_factureros)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table = QtWidgets.QTableView(self.frame)
        self.table.setObjectName("table")
        self.gridLayout_2.addWidget(self.table, 0, 0, 1, 6)
        self.btn_add = QtWidgets.QPushButton(self.frame)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout_2.addWidget(self.btn_add, 2, 0, 1, 2)
        self.btn_edit = QtWidgets.QPushButton(self.frame)
        self.btn_edit.setObjectName("btn_edit")
        self.gridLayout_2.addWidget(self.btn_edit, 2, 2, 1, 2)
        self.btn_delete = QtWidgets.QPushButton(self.frame)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout_2.addWidget(self.btn_delete, 2, 4, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(table_factureros)
        QtCore.QMetaObject.connectSlotsByName(table_factureros)

    def retranslateUi(self, table_factureros):
        _translate = QtCore.QCoreApplication.translate
        table_factureros.setWindowTitle(_translate("table_factureros", "Listado Factureros"))
        self.lbl_test.setText(_translate("table_factureros", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Texto de Prueba</span></p></body></html>"))
        self.btn_add.setText(_translate("table_factureros", "Agregar"))
        self.btn_edit.setText(_translate("table_factureros", "Editar"))
        self.btn_delete.setText(_translate("table_factureros", "Borrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    table_factureros = QtWidgets.QWidget()
    ui = Ui_table_factureros()
    ui.setupUi(table_factureros)
    table_factureros.show()
    sys.exit(app.exec_())
