# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_siif.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_siif(object):
    def setupUi(self, table_siif):
        table_siif.setObjectName("table_siif")
        table_siif.resize(796, 496)
        self.gridLayout = QtWidgets.QGridLayout(table_siif)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(table_siif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.table_imputaciones = QtWidgets.QTableView(self.groupBox_2)
        self.table_imputaciones.setObjectName("table_imputaciones")
        self.gridLayout_3.addWidget(self.table_imputaciones, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(table_siif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table_comprobantes = QtWidgets.QTableView(self.groupBox)
        self.table_comprobantes.setObjectName("table_comprobantes")
        self.gridLayout_2.addWidget(self.table_comprobantes, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(table_siif)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.table_retenciones = QtWidgets.QTableView(self.groupBox_3)
        self.table_retenciones.setObjectName("table_retenciones")
        self.gridLayout_4.addWidget(self.table_retenciones, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 1)

        self.retranslateUi(table_siif)
        QtCore.QMetaObject.connectSlotsByName(table_siif)

    def retranslateUi(self, table_siif):
        _translate = QtCore.QCoreApplication.translate
        table_siif.setWindowTitle(_translate("table_siif", "Comprobantes SIIF"))
        self.groupBox_2.setTitle(_translate("table_siif", "GroupBox"))
        self.groupBox.setTitle(_translate("table_siif", "GroupBox"))
        self.groupBox_3.setTitle(_translate("table_siif", "GroupBox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    table_siif = QtWidgets.QWidget()
    ui = Ui_table_siif()
    ui.setupUi(table_siif)
    table_siif.show()
    sys.exit(app.exec_())
