# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_factureros.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_factureros(object):
    def setupUi(self, table_factureros):
        table_factureros.setObjectName("table_factureros")
        table_factureros.resize(450, 500)
        self.gridLayout = QtWidgets.QGridLayout(table_factureros)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(table_factureros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 430, 455))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.table.setObjectName("table")
        self.gridLayout_2.addWidget(self.table, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_add = QtWidgets.QPushButton(self.frame)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout_3.addWidget(self.btn_add, 0, 2, 1, 1)
        self.btn_del = QtWidgets.QPushButton(self.frame)
        self.btn_del.setObjectName("btn_del")
        self.gridLayout_3.addWidget(self.btn_del, 0, 4, 1, 1)
        self.btn_edit = QtWidgets.QPushButton(self.frame)
        self.btn_edit.setObjectName("btn_edit")
        self.gridLayout_3.addWidget(self.btn_edit, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.lbl_test = QtWidgets.QLabel(table_factureros)
        self.lbl_test.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_test.setObjectName("lbl_test")
        self.gridLayout.addWidget(self.lbl_test, 1, 0, 1, 1)

        self.retranslateUi(table_factureros)
        QtCore.QMetaObject.connectSlotsByName(table_factureros)

    def retranslateUi(self, table_factureros):
        _translate = QtCore.QCoreApplication.translate
        table_factureros.setWindowTitle(_translate("table_factureros", "Listado Factureros"))
        self.btn_add.setText(_translate("table_factureros", "Agregar"))
        self.btn_del.setText(_translate("table_factureros", "Borrar"))
        self.btn_edit.setText(_translate("table_factureros", "Editar"))
        self.lbl_test.setText(_translate("table_factureros", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Texto de Prueba</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    table_factureros = QtWidgets.QWidget()
    ui = Ui_table_factureros()
    ui.setupUi(table_factureros)
    table_factureros.show()
    sys.exit(app.exec_())
